package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorDesencriptado;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * VISTA DESENCRIPTADO.Esta vista se encarga de manejar todo sobre el
 * desencriptado de un documento tendremos un menu para abri, cerrar y salir.
 *
 * ruta String - Se le pasara la ruta donde se desea guardar
 * texto String - Se le pasara el texto del textArea
 * controladorDesencriptado ControladorDesencriptado - Se almacenara el
 * objeto que controla el Encriptado.
 *
 * @author Paul Idrovo, Dennis Dutan
 */
public class DesEncriptacion extends javax.swing.JFrame {

    private String ruta;
    private String texto;
    private ControladorDesencriptado controladorDesencriptado;

    /**
     * CONSTRUCTOR. Se inicializa los componentes graficos y las variables
     * globales
     */
    public DesEncriptacion() {
        initComponents();
        this.ruta = "";
        this.texto = "";
        this.controladorDesencriptado = new ControladorDesencriptado();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/carpeta.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaTexto = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnAbrir = new javax.swing.JMenuItem();
        mnCerrar = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DESENCRIPTADO DE DOCUMENTOS");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("TEXTO DESENCRIPTADO:");

        txtaTexto.setColumns(20);
        txtaTexto.setRows(5);
        jScrollPane1.setViewportView(txtaTexto);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        mnAbrir.setMnemonic('o');
        mnAbrir.setText("Abrir");
        mnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAbrirActionPerformed(evt);
            }
        });
        fileMenu.add(mnAbrir);

        mnCerrar.setMnemonic('o');
        mnCerrar.setText("Cerrar");
        mnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCerrarActionPerformed(evt);
            }
        });
        fileMenu.add(mnCerrar);

        mnSalir.setMnemonic('o');
        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        fileMenu.add(mnSalir);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * OPCION MENU ABRIR. Mediante el evento de action performed se ejecuta el
     * JFileChooser el mismo que nos ayudara a buscar la ruta de donde deseamos
     * guardar. Este se puede personalizar segun nuestras necesidades, en este
     * caso fc.setDialogTitle("") se le pasa un titulo dependiendo la necesidad
     * del programador, en este caso es BUSCAR DOCUMENTO.
     * fc.setCurrentDirectory(File) se le pasa ob objeto tipo file que debe
     * tener la ruta donde deseamos que se abra como predeterminado, en caso de
     * no encontrarla se ira a la ruta predeterminada del sistema de Documentos.
     * fc.setFileFilter(FileNameExtensionFilter) se le pasa el tipo de archivos
     * que el usuario debe elegir, el primer atributo es el nombre que queremos
     * para visualizar y el segundo la extencion del archivo. Y abrimos la
     * ventana de abiri mediante fc.showOpenDialog;
     *
     * Luego de tener la ruta mediante FileReader leemos el documento y le
     * desencriptamos el texto por el metodo desencriptar del controlador
     * Desencriptado. Al final pasamos al text Area para la visualizacion del
     * usuario.
     *
     * @see FileWriter
     * @see JFileChooser
     * @see ControladorEncriptado
     * @param evt
     */
    private void mnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAbrirActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("BUSCAR DOCUMENTO");
        fc.setCurrentDirectory(new File("D:\\"));
        fc.setFileFilter(new FileNameExtensionFilter("Notas.txt", "txt"));
        if (fc.showOpenDialog(this) == 0) {
            ruta = fc.getSelectedFile().toString();
        }
        try {
            FileReader archivoLectura = new FileReader(ruta);
            BufferedReader lectura = new BufferedReader(archivoLectura);
            texto = "";
            String linea = "";
            while ((linea = lectura.readLine()) != null) {
                texto += linea;
            }
            lectura.close();
        } catch (FileNotFoundException e1) {
            System.out.println("Ruta de archivo no encontrada");
        } catch (IOException e2) {
            System.out.println("Error de lectura");
        } catch (Exception e3) {
            System.out.println("Error General");
        }
        txtaTexto.setText(controladorDesencriptado.desencriptar(texto));
    }//GEN-LAST:event_mnAbrirActionPerformed
    /**
     * OPCION MENU CERRAR. Esta opcion del menu nos ayuda para cerrar el
     * documento si lo abrimos por accidente.
     *
     * @param evt
     */
    private void mnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCerrarActionPerformed
        txtaTexto.setEditable(false);
        txtaTexto.setText("");
    }//GEN-LAST:event_mnCerrarActionPerformed

    /**
     * OPCION MENU SALIR. Esta opcion del menu nos ayuda para salir del
     * programa.
     *
     * @param evt
     */
    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesEncriptacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesEncriptacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesEncriptacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesEncriptacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    System.out.println("Error setting Java LAF: " + e);
                }
                new DesEncriptacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnAbrir;
    private javax.swing.JMenuItem mnCerrar;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JTextArea txtaTexto;
    // End of variables declaration//GEN-END:variables

}
